# keep flavors consistent with config/routes/annotations.yaml

liip_theme:
  themes: ['app', 'pocketcode', 'pocketalice', 'pocketgalaxy', 'phirocode', 'luna', 'create@school', 'embroidery', 'arduino']
  active_theme: 'app'

# used to access all themes via php
parameters:
  themes: ['pocketcode', 'pocketalice', 'pocketgalaxy', 'phirocode', 'luna', 'create@school', 'embroidery', 'arduino']
#  themes: ['pocketcode'] # switch while debugging for fast grunt builds
