version: '3.7'

services:

  # APACHE WITH PHP
  app.catroweb.test:
    build:
      args:
        - APP_ENVIRONMENT=test
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app.catroweb.test
    image: app.catroweb.test
    command: ["sh", "/var/www/catroweb/docker/app/startup-test.sh"]
    depends_on:
      - chrome.catroweb.test
    ports:
      - 8080:80

  chrome.catroweb.test:
    image: zenika/alpine-chrome
    container_name: chrome.catroweb.test
    command: ["chromium-browser", "--headless", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
    ports:
      - 9222