version: '3.7'

services:

  # APACHE WITH PHP
  app.catroweb.test:
    build:
      args:
        - APP_ENVIRONMENT=test
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app.catroweb.test
    image: app.catroweb.test
    command: ["sh", "/var/www/catroweb/docker/app/startup-test.sh"]
    depends_on:
      - db.catroweb.test
      - chrome.catroweb.test
    ports:
      - 8080:80

  # DATABASE
  db.catroweb.test:
    image: mariadb:10.3.11
    container_name: db.catroweb.test
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=catroweb_test

  chrome.catroweb.test:
    image: zenika/alpine-chrome
    container_name: chrome.catroweb.test
    volumes:
      - ./../tests/testdata/DataFixtures:/var/www/catroweb/tests/testdata/DataFixtures:ro
    command: ["chromium-browser", "--headless", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
    ports:
      - 9222