version: '3.7'

services:

  # APACHE WITH PHP
  app.catroweb.dev:
    build:
      args:
        - APP_ENVIRONMENT=dev
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app.catroweb.dev
    image: app.catroweb.dev
    depends_on:
      - db.catroweb.dev
      - chrome.catroweb.dev
    ports:
      - 8080:80
    volumes:
      - ./../assets:/var/www/catroweb/assets:cached
      - ./../tests:/var/www/catroweb/tests:cached
      - ./../templates:/var/www/catroweb/templates:cached
      - ./../translations:/var/www/catroweb/translations:cached
      - ./../src:/var/www/catroweb/src:cached
      - /var/www/vendor
      - /var/www/node_modules
    command: ["sh", "/var/www/catroweb/docker/app/startup.sh"]

  # DATABASE
  db.catroweb.dev:
    image: mariadb:10.3.11
    container_name: db.catroweb.dev
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=catroweb_dev

  chrome.catroweb.dev:
    image: zenika/alpine-chrome
    container_name: chrome.catroweb.dev
    restart: on-failure
    volumes:
      - ./../tests/testdata/DataFixtures:/var/www/catroweb/tests/testdata/DataFixtures:ro
    command: ["chromium-browser", "--headless", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
    ports:
      - 9222

  # PHPMYADMIN
  phpmyadmin.catroweb.dev:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin.catroweb.dev
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80
    volumes:
      - /sessions
    external_links:
      - db.catroweb.dev:db
    depends_on:
      - db.catroweb.dev
