monolog:
  channels: [upload, download_stats]
  handlers:

    main:
      type:  fingers_crossed
      action_level: error
      handler: nested
      # ToDo: Starting with Symfony 4.1 we can filter specific http for specific paths
      # excluded_http_codes: [{404: ['^/program', '^/user']}]
    nested:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.log"
      level: info
      max_files: 60

    upload:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%/upload/upload.log"
      level: warning
      max_files: 60
      channels: [upload]

    download_stats:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%/download_stats/download_stats.log"
      level: debug
      max_files: 60
      channels: [download_stats]

    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]

    deprecation:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.deprecations.log"
    deprecation_filter:
      type: filter
      handler: deprecation
      max_level: info
      channels: ["php"]