
name: Deployment

on:
  push:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Connect to TUG via VPN
        run: |
          sudo apt-get --yes --force-yes install openconnect
          printf '${{ secrets.VPN_PASSWD }}' | sudo openconnect vpn.tugraz.at --user=${{ secrets.VPN_USER }} & disown

      - name: Set Config Secrets
        run: |
          printf '\nDEPLOY_GIT=https://github.com/Catrobat/Catroweb-Symfony.git\n' >> .env.local
          printf 'DEPLOY_WEBTEST=${{ secrets.DEP_WEBTEST_HOST }}\n' >> .env.local
          printf 'DEPLOY_WEBTEST_BRANCH="master"\n' >> .env.local

      - name: Build Container
        run: |
          cd docker
          docker-compose -f docker-compose.test.yml build
          docker-compose -f docker-compose.test.yml up -d
          docker exec app.catroweb.test apt-get --yes --force-yes install ssh

      - name: Install SSH key on Host
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEP_WEBTEST_SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.DEP_WEBTEST_KNOWN_HOSTS }}
          # config: ${{ secrets.CONFIG }} # optional

      - name: Install SSH key in container
        run: |
          docker cp ~/.ssh app.catroweb.test:/root/.ssh
          docker exec app.catroweb.test chmod -R 777 /root/.ssh
      - name: Deploy
        run:
          docker exec app.catroweb.test bin/dep deploy web-test
