
# Runs all PhpUnit tests via docker in the latest ubuntu build

name: PhpUnit Tests

on: [push, pull_request] # ToDo for next version: trigger manually


jobs:

  tests_phpunit:
    name: PhpUnit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd docker
          docker-compose -f docker-compose.test.yml build
          docker-compose -f docker-compose.test.yml up -d

      - name: PhpUnit tests
        run:
          docker exec app.catroweb.test bin/phpunit tests